// packages/android/src/components/ColorPicker.tsx
import { LinearGradient } from 'expo-linear-gradient';
import React, { useCallback, useEffect, useRef, useState } from 'react';
import { LayoutChangeEvent, StyleSheet, View } from 'react-native';
import { Gesture, GestureDetector } from 'react-native-gesture-handler';
import Animated, {
  interpolateColor,
  runOnJS,
  useAnimatedStyle,
  useSharedValue,
} from 'react-native-reanimated';

import { hexToHsv, hsvToHex } from '../lib/color';
import { haptics } from '../lib/haptics';
import { radius, spacing, useTheme } from '../theme';

const SV_HEIGHT = 150;
const HUE_HEIGHT = 14;
const SV_THUMB = 22;
const HUE_THUMB = 22;

// Even rainbow around the hue wheel. interpolateColor (SV background) and the
// hue track LinearGradient share the same stops so they stay in agreement.
const HUE_STOPS = [0, 60, 120, 180, 240, 300, 360];
const HUE_COLORS = ['#ff0000', '#ffff00', '#00ff00', '#00ffff', '#0000ff', '#ff00ff', '#ff0000'];
const HUE_LOCATIONS = [0, 1 / 6, 2 / 6, 3 / 6, 4 / 6, 5 / 6, 1];

type Props = {
  /** Current color as a hex string, e.g. "#7c3aed". */
  value: string;
  /** Fires continuously while dragging — re-theme live, don't persist. */
  onPreview: (hex: string) => void;
  /** Fires once when a gesture settles — persist this value. */
  onCommit: (hex: string) => void;
};

/**
 * Saturation/brightness square + hue slider, in the same pan-gesture idiom as
 * Slider.tsx. HSV lives in shared values (UI thread) for smooth dragging; the
 * resolved hex is handed back to JS via runOnJS.
 */
export function ColorPicker({ value, onPreview, onCommit }: Props) {
  const { theme } = useTheme();
  const [svW, setSvW] = useState(0);
  const [hueW, setHueW] = useState(0);

  const start = hexToHsv(value) ?? { h: 160, s: 0.8, v: 0.7 };
  const hue = useSharedValue(start.h);
  const sat = useSharedValue(start.s);
  const val = useSharedValue(start.v);

  // The last hex we emitted. Used to (a) dedupe preview spam and (b) ignore the
  // parent echoing our own value back so the sync effect doesn't fight a drag.
  const lastHex = useRef<string>(value);

  // Preview throttle (~30 Hz, trailing edge). Every preview re-themes the
  // whole app — all four mode screens stay mounted and re-render per emit —
  // so forwarding raw gesture-event rate (60-120 Hz) drops frames on the
  // JS thread for no visible gain. The commit path stays unthrottled.
  const PREVIEW_MS = 33;
  const previewTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const pendingPreview = useRef<string | null>(null);
  const lastPreviewAt = useRef(0);
  // The hex most recently HANDED to the parent (throttle can hold newer
  // ones back) — the sync effect needs it to recognize stale echoes.
  const lastDelivered = useRef<string>(value);

  useEffect(
    () => () => {
      if (previewTimer.current) clearTimeout(previewTimer.current);
    },
    []
  );

  const emit = useCallback(
    (h: number, s: number, v: number, commit: boolean) => {
      const hex = hsvToHex(h, s, v);
      if (commit) {
        if (previewTimer.current) {
          clearTimeout(previewTimer.current);
          previewTimer.current = null;
        }
        pendingPreview.current = null;
        lastHex.current = hex;
        lastDelivered.current = hex;
        onCommit(hex);
      } else if (hex !== lastHex.current) {
        lastHex.current = hex;
        const now = Date.now();
        if (now - lastPreviewAt.current >= PREVIEW_MS) {
          lastPreviewAt.current = now;
          lastDelivered.current = hex;
          onPreview(hex);
        } else {
          pendingPreview.current = hex;
          if (!previewTimer.current) {
            previewTimer.current = setTimeout(() => {
              previewTimer.current = null;
              if (pendingPreview.current !== null) {
                lastPreviewAt.current = Date.now();
                const hexToSend = pendingPreview.current;
                pendingPreview.current = null;
                lastDelivered.current = hexToSend;
                onPreview(hexToSend);
              }
            }, PREVIEW_MS);
          }
        }
      }
    },
    [onCommit, onPreview]
  );

  // External value change (preset tap, reset, typed hex) → move the thumbs.
  // Skip our own preview echoes (value === lastHex) to avoid a feedback
  // loop. lastDelivered matters because the throttle advances lastHex
  // AHEAD of what the parent has actually received — an echo of the
  // previously delivered hex mid-drag must not snap the thumbs back.
  useEffect(() => {
    if (value === lastHex.current || value === lastDelivered.current) return;
    if (pendingPreview.current !== null) return; // mid-drag, echoes are stale
    const hsv = hexToHsv(value);
    if (!hsv) return;
    hue.value = hsv.h;
    sat.value = hsv.s;
    val.value = hsv.v;
    lastHex.current = value;
  }, [value, hue, sat, val]);

  const svPan = Gesture.Pan()
    .minDistance(0)
    .onBegin((e) => {
      runOnJS(haptics.tap)();
      if (svW <= 0) return;
      const s = clamp01(e.x / svW);
      const v = 1 - clamp01(e.y / SV_HEIGHT);
      sat.value = s;
      val.value = v;
      runOnJS(emit)(hue.value, s, v, false);
    })
    .onChange((e) => {
      if (svW <= 0) return;
      const s = clamp01(e.x / svW);
      const v = 1 - clamp01(e.y / SV_HEIGHT);
      sat.value = s;
      val.value = v;
      runOnJS(emit)(hue.value, s, v, false);
    })
    .onFinalize(() => {
      runOnJS(emit)(hue.value, sat.value, val.value, true);
    });

  const huePan = Gesture.Pan()
    .minDistance(0)
    .onBegin((e) => {
      runOnJS(haptics.tap)();
      if (hueW <= 0) return;
      const h = clamp01(e.x / hueW) * 360;
      hue.value = h;
      runOnJS(emit)(h, sat.value, val.value, false);
    })
    .onChange((e) => {
      if (hueW <= 0) return;
      const h = clamp01(e.x / hueW) * 360;
      hue.value = h;
      runOnJS(emit)(h, sat.value, val.value, false);
    })
    .onFinalize(() => {
      runOnJS(emit)(hue.value, sat.value, val.value, true);
    });

  const svBg = useAnimatedStyle(() => ({
    backgroundColor: interpolateColor(hue.value, HUE_STOPS, HUE_COLORS),
  }));
  const svThumb = useAnimatedStyle(() => ({
    transform: [
      { translateX: sat.value * svW - SV_THUMB / 2 },
      { translateY: (1 - val.value) * SV_HEIGHT - SV_THUMB / 2 },
    ],
  }));
  const hueThumb = useAnimatedStyle(() => ({
    transform: [{ translateX: (hue.value / 360) * hueW - HUE_THUMB / 2 }],
  }));

  return (
    <View style={styles.container}>
      <GestureDetector gesture={svPan}>
        <View
          onLayout={(e: LayoutChangeEvent) => setSvW(e.nativeEvent.layout.width)}
          style={styles.svWrap}
        >
          <Animated.View style={[styles.svSquare, { borderColor: theme.border.subtle }, svBg]}>
            <LinearGradient
              colors={['#ffffff', 'rgba(255,255,255,0)'] as const}
              start={{ x: 0, y: 0 }}
              end={{ x: 1, y: 0 }}
              style={StyleSheet.absoluteFill}
              pointerEvents="none"
            />
            <LinearGradient
              colors={['rgba(0,0,0,0)', '#000000'] as const}
              start={{ x: 0, y: 0 }}
              end={{ x: 0, y: 1 }}
              style={StyleSheet.absoluteFill}
              pointerEvents="none"
            />
          </Animated.View>
          <Animated.View style={[styles.svThumb, svThumb]} pointerEvents="none" />
        </View>
      </GestureDetector>

      <GestureDetector gesture={huePan}>
        <View
          onLayout={(e: LayoutChangeEvent) => setHueW(e.nativeEvent.layout.width)}
          style={styles.hueTrackWrap}
        >
          <LinearGradient
            colors={HUE_COLORS as unknown as readonly [string, string, ...string[]]}
            locations={HUE_LOCATIONS as unknown as readonly [number, number, ...number[]]}
            start={{ x: 0, y: 0.5 }}
            end={{ x: 1, y: 0.5 }}
            style={[styles.hueTrack, { borderColor: theme.border.subtle }]}
          />
          <Animated.View style={[styles.hueThumb, hueThumb]} pointerEvents="none" />
        </View>
      </GestureDetector>
    </View>
  );
}

function clamp01(n: number): number {
  'worklet';
  return Math.min(1, Math.max(0, n));
}

const styles = StyleSheet.create({
  container: { gap: spacing.lg },
  svWrap: {
    height: SV_HEIGHT,
    justifyContent: 'flex-start',
  },
  svSquare: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: radius.xs,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
  },
  svThumb: {
    position: 'absolute',
    width: SV_THUMB,
    height: SV_THUMB,
    borderRadius: SV_THUMB / 2,
    borderWidth: 3,
    borderColor: '#ffffff',
    backgroundColor: 'transparent',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.4,
    shadowRadius: 2,
    elevation: 3,
  },
  hueTrackWrap: {
    height: HUE_THUMB,
    justifyContent: 'center',
  },
  hueTrack: {
    height: HUE_HEIGHT,
    borderRadius: HUE_HEIGHT / 2,
    borderWidth: StyleSheet.hairlineWidth,
  },
  hueThumb: {
    position: 'absolute',
    width: HUE_THUMB,
    height: HUE_THUMB,
    borderRadius: HUE_THUMB / 2,
    borderWidth: 3,
    borderColor: '#ffffff',
    backgroundColor: 'transparent',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.4,
    shadowRadius: 2,
    elevation: 3,
  },
});

// packages/shared/src/components/ColorPicker.svelte
<script>
  import { onDestroy } from "svelte";
  import { hexToHsv, hsvToHex } from "../lib/color.js";

  /**
   * Saturation/brightness square + hue slider — port of the Android
   * ColorPicker (packages/android/src/components/ColorPicker.tsx), same
   * gesture idiom as ClipEditor's drag handles (pointerdown + window
   * listeners) so it works with mouse, pen and touch.
   */

  /** Current colour as a hex string, e.g. "#7c3aed". */
  export let value = "#10b981";
  /** Fires continuously while dragging — re-theme live, don't persist. */
  export let onPreview = () => {};
  /** Fires once when a gesture settles — persist this value. */
  export let onCommit = () => {};

  const start = hexToHsv(value) ?? { h: 160, s: 0.8, v: 0.7 };
  let hue = start.h;
  let sat = start.s;
  let val = start.v;

  let svEl;
  let hueEl;
  let dragging = null; // "sv" | "hue" | null

  // The last hex we produced. Used to (a) dedupe preview spam and (b) ignore
  // the parent echoing our own value back so the sync below doesn't fight a
  // drag.
  let lastHex = value;
  // The hex most recently HANDED to the parent (the throttle can hold newer
  // ones back) — needed to recognise stale echoes.
  let lastDelivered = value;

  // Preview throttle (~30 Hz, trailing edge). Every preview rewrites the
  // root custom properties and restyles the whole document, so forwarding
  // raw pointer-event rate (60-144 Hz) burns layout for no visible gain.
  // The commit path stays unthrottled.
  const PREVIEW_MS = 33;
  let previewTimer = null;
  let pendingPreview = null;
  let lastPreviewAt = 0;

  onDestroy(() => {
    if (previewTimer) clearTimeout(previewTimer);
    stopDrag();
  });

  function emit(commit) {
    const hex = hsvToHex(hue, sat, val);
    if (commit) {
      if (previewTimer) {
        clearTimeout(previewTimer);
        previewTimer = null;
      }
      pendingPreview = null;
      lastHex = hex;
      lastDelivered = hex;
      onCommit(hex);
      return;
    }
    if (hex === lastHex) return;
    lastHex = hex;
    const now = Date.now();
    if (now - lastPreviewAt >= PREVIEW_MS) {
      lastPreviewAt = now;
      lastDelivered = hex;
      onPreview(hex);
    } else {
      pendingPreview = hex;
      if (!previewTimer) {
        previewTimer = setTimeout(() => {
          previewTimer = null;
          if (pendingPreview === null) return;
          lastPreviewAt = Date.now();
          const next = pendingPreview;
          pendingPreview = null;
          lastDelivered = next;
          onPreview(next);
        }, PREVIEW_MS);
      }
    }
  }

  // External value change (swatch tap, reset, typed hex) → move the thumbs.
  // Skip our own echoes to avoid a feedback loop: lastDelivered matters
  // because the throttle advances lastHex AHEAD of what the parent has
  // actually received, and an echo of the previously delivered hex mid-drag
  // must not snap the thumbs back.
  $: syncExternal(value);

  function syncExternal(v) {
    if (v === lastHex || v === lastDelivered) return;
    if (pendingPreview !== null) return; // mid-drag, echoes are stale
    const hsv = hexToHsv(v);
    if (!hsv) return;
    hue = hsv.h;
    sat = hsv.s;
    val = hsv.v;
    lastHex = v;
    lastDelivered = v;
  }

  const clamp01 = (n) => Math.min(1, Math.max(0, n));

  function applySv(clientX, clientY) {
    if (!svEl) return;
    const r = svEl.getBoundingClientRect();
    if (r.width <= 0 || r.height <= 0) return;
    sat = clamp01((clientX - r.left) / r.width);
    val = 1 - clamp01((clientY - r.top) / r.height);
    emit(false);
  }

  function applyHue(clientX) {
    if (!hueEl) return;
    const r = hueEl.getBoundingClientRect();
    if (r.width <= 0) return;
    hue = clamp01((clientX - r.left) / r.width) * 360;
    emit(false);
  }

  function onDown(which, e) {
    e.preventDefault();
    dragging = which;
    if (which === "sv") applySv(e.clientX, e.clientY);
    else applyHue(e.clientX);
    window.addEventListener("pointermove", onMove, true);
    window.addEventListener("pointerup", onUp, true);
    window.addEventListener("pointercancel", onUp, true);
  }

  function onMove(e) {
    if (!dragging) return;
    e.preventDefault();
    if (dragging === "sv") applySv(e.clientX, e.clientY);
    else applyHue(e.clientX);
  }

  function onUp() {
    if (!dragging) return;
    stopDrag();
    emit(true);
  }

  function stopDrag() {
    dragging = null;
    if (typeof window === "undefined") return;
    window.removeEventListener("pointermove", onMove, true);
    window.removeEventListener("pointerup", onUp, true);
    window.removeEventListener("pointercancel", onUp, true);
  }

  // Keyboard nudges — the square moves saturation/brightness, the track hue.
  // Each keypress is its own committed change (no drag to settle).
  function onSvKey(e) {
    const step = e.shiftKey ? 0.1 : 0.02;
    let handled = true;
    if (e.key === "ArrowLeft") sat = clamp01(sat - step);
    else if (e.key === "ArrowRight") sat = clamp01(sat + step);
    else if (e.key === "ArrowUp") val = clamp01(val + step);
    else if (e.key === "ArrowDown") val = clamp01(val - step);
    else handled = false;
    if (!handled) return;
    e.preventDefault();
    emit(true);
  }

  function onHueKey(e) {
    const step = e.shiftKey ? 24 : 4;
    let handled = true;
    if (e.key === "ArrowLeft") hue = (hue - step + 360) % 360;
    else if (e.key === "ArrowRight") hue = (hue + step) % 360;
    else if (e.key === "Home") hue = 0;
    else if (e.key === "End") hue = 359;
    else handled = false;
    if (!handled) return;
    e.preventDefault();
    emit(true);
  }

  $: hueBase = hsvToHex(hue, 1, 1);
  $: swatch = hsvToHex(hue, sat, val);
</script>

<div class="picker">
  <div
    class="sv"
    class:dragging={dragging === "sv"}
    bind:this={svEl}
    role="slider"
    tabindex="0"
    aria-label="Saturation and brightness"
    aria-valuemin="0"
    aria-valuemax="100"
    aria-valuenow={Math.round(sat * 100)}
    aria-valuetext={`saturation ${Math.round(sat * 100)}%, brightness ${Math.round(val * 100)}%`}
    style={`background-color: ${hueBase}`}
    on:pointerdown={(e) => onDown("sv", e)}
    on:keydown={onSvKey}
  >
    <div class="sv-white"></div>
    <div class="sv-black"></div>
    <div
      class="thumb sv-thumb"
      style={`left: ${sat * 100}%; top: ${(1 - val) * 100}%; background: ${swatch}`}
    ></div>
  </div>

  <div
    class="hue"
    class:dragging={dragging === "hue"}
    bind:this={hueEl}
    role="slider"
    tabindex="0"
    aria-label="Hue"
    aria-valuemin="0"
    aria-valuemax="360"
    aria-valuenow={Math.round(hue)}
    on:pointerdown={(e) => onDown("hue", e)}
    on:keydown={onHueKey}
  >
    <div
      class="thumb hue-thumb"
      style={`left: ${(hue / 360) * 100}%; background: ${hueBase}`}
    ></div>
  </div>
</div>

<style>
  .picker {
    display: flex;
    flex-direction: column;
    gap: 14px;
  }

  .sv {
    position: relative;
    height: 150px;
    border-radius: var(--radius-xs);
    border: 1px solid var(--border);
    cursor: crosshair;
    touch-action: none;
    overflow: hidden;
  }

  .sv-white,
  .sv-black {
    position: absolute;
    inset: 0;
    pointer-events: none;
  }

  .sv-white { background: linear-gradient(to right, #ffffff, rgba(255, 255, 255, 0)); }
  .sv-black { background: linear-gradient(to bottom, rgba(0, 0, 0, 0), #000000); }

  .hue {
    position: relative;
    height: 14px;
    border-radius: 999px;
    border: 1px solid var(--border);
    cursor: pointer;
    touch-action: none;
    background: linear-gradient(
      to right,
      #ff0000 0%,
      #ffff00 16.666%,
      #00ff00 33.333%,
      #00ffff 50%,
      #0000ff 66.666%,
      #ff00ff 83.333%,
      #ff0000 100%
    );
  }

  .sv:focus-visible,
  .hue:focus-visible {
    outline: 2px solid var(--accent);
    outline-offset: 2px;
  }

  .thumb {
    position: absolute;
    width: 18px;
    height: 18px;
    border-radius: 50%;
    border: 3px solid #ffffff;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.45);
    pointer-events: none;
    transform: translate(-50%, -50%);
  }

  .sv-thumb { transition: none; }

  .hue-thumb {
    top: 50%;
    width: 20px;
    height: 20px;
  }

  .sv.dragging,
  .hue.dragging {
    /* Keeps the cursor from flickering while the pointer leaves the box. */
    cursor: grabbing;
  }
</style>
