// packages/android/src/components/convert/OutputSettings.tsx
import React, { useEffect, useState } from 'react';
import { StyleSheet, Text, TextInput, View } from 'react-native';

import { Slider } from '../Slider';
import { radius, spacing, typography, useTheme } from '../../theme';

type Props = {
  /** Show a filename input if this is a single-file conversion. */
  singleFileName?: string;
  /** Target format extension to show as a trailing badge after the filename. */
  formatExt?: string;
  onFilenameChange?: (name: string) => void;

  quality: number;
  onQualityChange: (q: number) => void;
  qualityKind?: 'image' | 'video' | 'audio';
  /** Hide the quality slider (e.g. GIF, whose palette pipeline ignores it). */
  showQuality?: boolean;

  /** Target output size in MB. null = off (quality slider drives the encode). */
  targetSizeMb?: number | null;
  onTargetSizeChange?: (mb: number | null) => void;
  /** Show the target-size field — video targets only. */
  showTargetSize?: boolean;
};

/** Empty / zero / garbage all mean "off" — the field can never hard-error. */
function parseTargetSize(text: string): number | null {
  // Accept a decimal comma (German locale keyboards emit one).
  const n = parseFloat(text.replace(',', '.'));
  return Number.isFinite(n) && n > 0 ? n : null;
}

const QUALITY_KIND_COPY: Record<string, { label: string; hi: string }> = {
  image: { label: 'Image quality', hi: 'Sharper' },
  video: { label: 'Bitrate quality', hi: 'Higher bitrate' },
  audio: { label: 'Audio quality', hi: 'Higher bitrate' },
};

/**
 * Port of desktop OutputSettings.svelte.
 *
 * Filename input (single-file mode only) + quality slider with low/high
 * end-labels. Mobile drops desktop's output-directory picker — the export
 * goes to Convert-X gallery album / share intent.
 */
export function OutputSettings({
  singleFileName,
  formatExt,
  onFilenameChange,
  quality,
  onQualityChange,
  qualityKind = 'image',
  showQuality = true,
  targetSizeMb,
  onTargetSizeChange,
  showTargetSize = false,
}: Props) {
  const { theme } = useTheme();
  const copy = QUALITY_KIND_COPY[qualityKind] ?? QUALITY_KIND_COPY.image;

  // The field owns its raw text so partial input ("1." / "0,") survives the
  // controlled round-trip; only the parsed value goes up to settings.
  const [sizeText, setSizeText] = useState(
    targetSizeMb != null ? String(targetSizeMb) : ''
  );
  useEffect(() => {
    // External change (reset, hydration) — re-sync unless the text already
    // parses to the incoming value, which would clobber in-progress typing.
    if ((targetSizeMb ?? null) !== parseTargetSize(sizeText)) {
      setSizeText(targetSizeMb != null ? String(targetSizeMb) : '');
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [targetSizeMb]);

  return (
    <View
      style={[
        styles.card,
        { backgroundColor: theme.bg.surface, borderColor: theme.border.subtle },
      ]}
    >
      {singleFileName !== undefined ? (
        <View style={styles.field}>
          <Text style={[styles.label, { color: theme.text.muted }]}>FILE NAME</Text>
          <View
            style={[
              styles.nameRow,
              {
                backgroundColor: theme.bg.surfaceSunken,
                borderColor: theme.border.subtle,
              },
            ]}
          >
            <TextInput
              value={singleFileName}
              onChangeText={onFilenameChange}
              placeholder="output"
              placeholderTextColor={theme.text.muted}
              style={[styles.nameInput, { color: theme.text.primary }]}
            />
            {formatExt ? (
              <Text style={[styles.ext, { color: theme.accent.primary }]}>.{formatExt}</Text>
            ) : null}
          </View>
        </View>
      ) : null}

      {showQuality ? (
        <View style={styles.field}>
          <Slider
            value={quality}
            onChange={onQualityChange}
            min={1}
            max={100}
            step={1}
            label={copy.label}
            suffix="%"
          />
          <View style={styles.sliderLabels}>
            <Text style={[styles.sliderLabel, { color: theme.text.muted }]}>Smaller</Text>
            <Text style={[styles.sliderLabel, { color: theme.text.muted }]}>{copy.hi}</Text>
          </View>
        </View>
      ) : null}

      {showTargetSize && onTargetSizeChange ? (
        <View style={styles.field}>
          <Text style={[styles.label, { color: theme.text.muted }]}>TARGET SIZE</Text>
          <View
            style={[
              styles.nameRow,
              {
                backgroundColor: theme.bg.surfaceSunken,
                borderColor: theme.border.subtle,
              },
            ]}
          >
            <TextInput
              value={sizeText}
              onChangeText={(text) => {
                setSizeText(text);
                onTargetSizeChange(parseTargetSize(text));
              }}
              placeholder="Off"
              placeholderTextColor={theme.text.muted}
              keyboardType="decimal-pad"
              style={[styles.nameInput, { color: theme.text.primary }]}
            />
            <Text style={[styles.ext, { color: theme.accent.primary }]}>MB</Text>
          </View>
          <Text style={[styles.sliderLabel, { color: theme.text.muted }]}>
            Fits the export under this size by overriding the quality slider.
            Leave empty to disable.
          </Text>
        </View>
      ) : null}
    </View>
  );
}

const styles = StyleSheet.create({
  card: {
    padding: spacing.xl,
    borderRadius: radius.sm,
    borderWidth: StyleSheet.hairlineWidth,
    gap: spacing.lg,
  },
  field: { gap: spacing.sm },
  label: { ...typography.micro, letterSpacing: 0.6 },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
    borderRadius: radius.xs,
    borderWidth: StyleSheet.hairlineWidth,
    gap: spacing.xs,
  },
  nameInput: {
    flex: 1,
    ...typography.bodySm,
    paddingVertical: 0,
  },
  ext: { ...typography.bodySm, fontWeight: '600' },
  sliderLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sliderLabel: { ...typography.tiny },
});

// packages/shared/src/components/OutputSettings.svelte
<script>
  import { getPlatform } from "../platform.js";

  export let outputDir;
  export let quality;
  export let selectedFormat;
  export let isBatch = false;
  export let singleOutputName = "";
  export let onNameChange;
  export let onDirChange;
  export let onQualityChange;
  // Target output size in MB. null = off (quality slider drives the encode).
  export let targetSizeMb = null;
  export let onTargetSizeChange = null;
  // Show the target-size field — video-category targets only (GIF excluded).
  export let showTargetSize = false;

  $: isWeb = getPlatform().platformType === "web";
  $: qualityLabel = selectedFormat === "gif" ? "GIF quality" : "Quality";
  $: qualityHighLabel = selectedFormat === "gif" ? "Cleaner" : "Better";

  // Empty / zero / garbage all mean "off" — the field can never hard-error.
  // Accepts a decimal comma (German locale keyboards emit one).
  function parseTargetSize(text) {
    const n = parseFloat(String(text).replace(",", "."));
    return Number.isFinite(n) && n > 0 ? n : null;
  }

  // The field owns its raw text so partial input ("1." / "0,") survives the
  // controlled round-trip; only the parsed value goes up to settings.
  let sizeText = targetSizeMb != null ? String(targetSizeMb) : "";

  // External change (reset, hydration) — re-sync unless the text already
  // parses to the incoming value, which would clobber in-progress typing.
  $: if ((targetSizeMb ?? null) !== parseTargetSize(sizeText)) {
    sizeText = targetSizeMb != null ? String(targetSizeMb) : "";
  }

  function onTargetSizeInput(e) {
    sizeText = e.target.value;
    onTargetSizeChange?.(parseTargetSize(sizeText));
  }

  async function pickFolder() {
    const result = await getPlatform().pickFolder();
    if (result) onDirChange(result);
  }

  function truncateDir(dir) {
    if (!dir) return "Same as source";
    if (dir.length <= 38) return dir;
    return "..." + dir.slice(-35);
  }
</script>

<div class="settings">
  <!-- Filename (single file only) -->
  {#if !isBatch}
    <div class="field">
      <span class="label">File name</span>
      <div class="input-row">
        <input
          type="text"
          class="name-input"
          value={singleOutputName}
          on:input={(e) => onNameChange(e.target.value)}
          placeholder="output filename"
          spellcheck="false"
        />
        {#if selectedFormat}
          <span class="ext">.{selectedFormat}</span>
        {/if}
      </div>
    </div>
  {/if}

  <!-- Output directory -->
  {#if !isWeb}
  <div class="field">
    <span class="label">Save to</span>
    <button class="dir-btn" on:click={pickFolder}>
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"/></svg>
      <span class="dir-path">{truncateDir(outputDir)}</span>
      <span class="change">Change</span>
    </button>
  </div>
  {/if}

  <div class="field">
    <div class="quality-head">
      <span class="label">{qualityLabel}</span>
      <span class="quality-val">{quality}%</span>
    </div>
    <div class="slider-wrap">
      <input
        type="range"
        min="1"
        max="100"
        value={quality}
        on:input={(e) => onQualityChange(parseInt(e.target.value))}
        class="slider"
        style="--val: {quality}%"
      />
      <div class="slider-labels">
        <span>Smaller</span>
        <span>{qualityHighLabel}</span>
      </div>
    </div>
  </div>

  <!-- Target size (video targets only, GIF excluded) -->
  {#if showTargetSize && onTargetSizeChange}
    <div class="field">
      <span class="label">Target size</span>
      <div class="input-row">
        <input
          type="text"
          class="name-input"
          inputmode="decimal"
          value={sizeText}
          on:input={onTargetSizeInput}
          placeholder="Off"
          spellcheck="false"
        />
        <span class="ext">MB</span>
      </div>
      <span class="field-hint">
        Fits the export under this size by overriding the quality slider.
        Leave empty to disable.
      </span>
    </div>
  {/if}
</div>

<style>
  .settings {
    background: var(--bg-card);
    border: 1px solid var(--border);
    border-radius: var(--radius-sm);
    padding: 14px;
    display: flex;
    flex-direction: column;
    gap: 12px;
    animation: fadeUp 0.35s ease-out;
  }

  .field { display: flex; flex-direction: column; gap: 5px; }

  .label {
    font-size: 0.68rem;
    color: var(--text-muted);
    text-transform: uppercase;
    letter-spacing: 0.08em;
    font-weight: 600;
  }

  .input-row {
    display: flex;
    align-items: center;
    background: var(--bg-input);
    border: 1px solid var(--border);
    border-radius: var(--radius-xs);
    padding: 0 10px;
    transition: border-color var(--transition-fast);
  }

  .input-row:focus-within { border-color: var(--accent-dim); }

  .name-input {
    flex: 1;
    padding: 8px 0;
    font-size: 0.82rem;
    min-width: 0;
    background: transparent;
    border: none;
    outline: none;
    color: var(--text-primary);
    font-family: inherit;
  }

  .name-input::placeholder { color: var(--text-muted); }

  .field-hint {
    font-size: 0.68rem;
    color: var(--text-muted);
  }

  .ext {
    color: var(--accent);
    font-size: 0.82rem;
    font-weight: 600;
    padding-left: 2px;
    flex-shrink: 0;
  }

  .dir-btn {
    display: flex;
    align-items: center;
    gap: 8px;
    background: var(--bg-input);
    border: 1px solid var(--border);
    border-radius: var(--radius-xs);
    padding: 8px 10px;
    color: var(--text-secondary);
    font-size: 0.78rem;
    text-align: left;
    transition: all var(--transition-fast);
  }

  .dir-btn:hover { border-color: var(--border-hover); background: var(--bg-hover); }
  .dir-btn svg { flex-shrink: 0; color: var(--text-muted); }
  .dir-path { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; min-width: 0; }
  .change { flex-shrink: 0; font-size: 0.7rem; color: var(--accent); font-weight: 600; }

  .quality-head { display: flex; justify-content: space-between; align-items: center; }
  .quality-head .label { margin-bottom: 0; }
  .quality-val { font-size: 0.78rem; color: var(--accent); font-weight: 700; font-variant-numeric: tabular-nums; }

  .slider-wrap { padding-top: 2px; }

  .slider {
    width: 100%;
    height: 4px;
    -webkit-appearance: none;
    appearance: none;
    border-radius: 2px;
    outline: none;
    background: linear-gradient(to right, var(--accent) 0%, var(--accent) var(--val), var(--border) var(--val), var(--border) 100%);
  }

  .slider::-webkit-slider-thumb {
    -webkit-appearance: none;
    width: 16px;
    height: 16px;
    border-radius: 50%;
    background: var(--accent);
    cursor: pointer;
    border: 2px solid var(--bg-card);
    box-shadow: 0 0 0 1px var(--accent-dim);
  }

  .slider::-webkit-slider-thumb:hover { box-shadow: 0 0 0 3px var(--accent-glow); }

  .slider-labels { display: flex; justify-content: space-between; margin-top: 4px; font-size: 0.65rem; color: var(--text-muted); }
</style>
